### PR TITLE
Make a first blog post

### PR DESCRIPTION
**Pull request by tmigot**
#19

### CODE REVIEW

**Comment by abelsiqueira** [comment]
@tmigot, I rebased your branch. I've implemented a blog post logic. Let me know what you think. In this logic, the news and tutorials don't run any code - so the main site remains lean.

**Comment by tmigot** [comment]
Awesome!!
Before we merge this, I will add more links to DCISolver.jl and the new paper in the reference section.

**Comment by tmigot** [comment]
It really took me a while to figure that `here` contains a link in the preview, because the green color is really close to the font color.
Is it the same on your browser?

**Comment by tmigot** [comment]
I added more links everywhere in the post. It's good for me now.

**Comment by dpo** [comment]
Great job! It's true that the links are barely visible.

**Pull request merged**
